import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const {data, isError, isLoading} = trpc.user.getUserByEmail.useQuery({email: "test@gmail.com"})

  console.log(data, isError, isLoading)

  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container flex flex-col items-center justify-center min-h-screen p-4 mx-auto gap-4">
        <h1 className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-slate-500 to-slate-900">Xtra Power</h1>
        {session ? (
          <div className="flex flex-col gap-4">
            <h2 className="text-xl text-slate-900">
              Signed in as {session.user?.name}
            </h2>
            <img
              src={session.user?.image as string}
              alt={session.user?.name as string}
              className="w-20 h-20 rounded-full mx-auto"
            />
            <div className="flex justify-center">
              <button onClick={() => signOut()}>Sign out</button>
            </div>
          </div>
        ) : (
          <div>
            <button
              onClick={() =>
                signIn("discord", {
                  callbackUrl: `/type-user`,
                })
              }
            >
              Sign in
            </button>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
